config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :permissions

  root 'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'welcome' => 'static_pages#welcome'
  get 'about'   => 'static_pages#about'
  get 'help'    => 'static_pages#help'
  get 'version/1.1' => 'static_pages#v1_1'
  get 'version/1.2' => 'static_pages#v1_2'

  get 'signin'  => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  resources :sessions, only: [:create, :destroy]

  get 'monitor/dashboard' => 'monitor#dashboard'
  get 'monitor' => 'monitor#dashboard'

  get 'admin/dashboard' => 'admin#dashboard'
  get 'admin' => 'admin#dashboard'

  get 'archive' => 'reservations#archive'

  resources :reservations do
    collection do
      get 'archive'
    end

    member do
      get 'approve'
      post 'deny'
      get 'checkout'
      post 'checkout_update'
      get 'checkin'
      post 'checkin_update'
    end
  end
  resources :equipment do
    member do
      get 'history'
    end

    resources :sub_items
  end
  resources :users do
    member do
      get 'password'
    end

    collection do
      get 'monitors'
      get 'admins'
    end
  end
  resources :reservation_equipment

  get 'search' => 'search#index', as: :search

end

app/views/admin/dashboard.html.erb
<% provide(:title, 'Admin Dashboard') %>

<h1 class="page-header">Admin Dashboard</h1>

<div class="row dashboard">
	<div class="col-sm-6">
		<%= render 'shared/user_reservation_list', reservations: @reservations_pending,
			title: 'Reservations Needing Approval', empty_text: 'There are no reservations that need approval', should_show_buttons: true %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Other Actions</h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
        <%= link_to archive_reservations_path, class: 'btn btn-large btn-primary' do %>
          <i class="fa fa-archive"></i> Archive
        <% end %>
        </li>
      </ul>
    </div>

	</div>
	<div class="col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Manage Permissions</h3>
			</div>
			<ul class="list-group">
				<li class="list-group-item">
					<%= link_to new_permission_path, class: 'btn btn-large btn-primary' do %>
						<i class="fa fa-plus"></i> New Permission
					<% end %>
				</li>
				<% @permissions.each do |permission| %>
				<li class="list-group-item">
					<%= link_to permission do %> <%= permission.name %> <% end %>
                    <%= link_to permission, class: 'btn btn-large pull-right', method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <i class="fa fa-trash-o"></i>
                    <% end %>
					<%= link_to edit_equipment_path(permission), class: 'btn btn-large pull-right' do %>
                        <i class="fa fa-pencil"></i>
                    <% end %>
				</li>
				<% end %>
			</ul>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">Manage Users</h2>
			</div>
			<ul class="list-group">
				<li class="list-group-item">
					<%= link_to users_path, class: 'btn btn-large btn-primary' do %>
						<i class="fa fa-users"></i> View Users
					<% end %>
				</li>
				<li class="list-group-item">
					<%= link_to new_user_path, class: 'btn btn-large btn-primary' do %>
						<i class="fa fa-plus"></i> New User
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</div>