config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :permissions

  root 'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'welcome' => 'static_pages#welcome'
  get 'about'   => 'static_pages#about'
  get 'help'    => 'static_pages#help'
  get 'version/1.1' => 'static_pages#v1_1'
  get 'version/1.2' => 'static_pages#v1_2'

  get 'signin'  => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  resources :sessions, only: [:create, :destroy]

  get 'monitor/dashboard' => 'monitor#dashboard'
  get 'monitor' => 'monitor#dashboard'

  get 'admin/dashboard' => 'admin#dashboard'
  get 'admin' => 'admin#dashboard'

  get 'archive' => 'reservations#archive'

  resources :reservations do
    collection do
      get 'archive'
    end

    member do
      get 'approve'
      post 'deny'
      get 'checkout'
      post 'checkout_update'
      get 'checkin'
      post 'checkin_update'
    end
  end
  resources :equipment do
    member do
      get 'history'
    end

    resources :sub_items
  end
  resources :users do
    member do
      get 'password'
    end

    collection do
      get 'monitors'
      get 'admins'
    end
  end
  resources :reservation_equipment

  get 'search' => 'search#index', as: :search

end

app/models/equipment.rb
# == Schema Information
#
# Table name: equipment
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  brand       :string(255)
#  quantity    :integer
#  condition   :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  description :string(255)
#  is_kit      :boolean
#  type        :integer
#  category_id :integer
#

class Equipment < ActiveRecord::Base
  has_many :reservation_equipment
  has_many :reservations, through: :reservation_equipment
  has_many :sub_items, :foreign_key => :kit_id, :class_name => 'SubItem'
  has_and_belongs_to_many :permissions
  belongs_to :category

  validates :name, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :condition, presence: true
  validates :description, presence: true

  def can_be_checked_out_by(user)
    permissions.each do |permission|
      user.permissions.each do |user_permission|
        if permission == user_permission
          return true
        end
      end
    end

    false
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment,  only: [:show, :edit, :update, :destroy, :history]
  before_filter :user_signed_in,  only: [:new, :edit, :create, :update, :destroy]
  before_filter :user_is_admin,  only: [:new, :edit, :create, :update, :destroy, :history]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  # GET /equipment/1/edit
  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html {
          if @equipment.is_kit?
            redirect_to new_equipment_sub_item_path(@equipment), notice: 'Please enter the items that make up this kit'
          else
            redirect_to @equipment, notice: 'Equipment was successfully created.'
          end
        }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /equipment/1/history
  def history
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:name, :brand, :quantity, :condition, :description, :is_kit, :category_id, permission_ids: [])
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<!-- ng-candidate: Have all equipment and sub-item forms in the same angular app -->
<div class="row">
  <%= form_for(@equipment) do |f| %>
    <div class="col-sm-6 col-sm-offset-1">

        <%= render 'shared/error_messages', object: f.object %>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :brand %>
          <%= f.text_field :brand, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :category %>
          <%= f.collection_select :category_id, Category.all, :id, :name %>
        </div>

        <div class="field">
          <%= f.label :quantity %>
          <%= f.number_field :quantity, min: 1, step: 1, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :condition %>
          <%= f.text_field :condition, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <%= f.submit "Save Equipment", class: 'btn btn-large btn-success' %>

    </div>
    <div class="col-sm-4">
      <h4>Permissions</h4>
      <ul class="permissions-list">
        <%= f.collection_check_boxes :permission_ids, Permission.all, :id, :name do |ff| %>
        <li><%= ff.check_box %> <%= ff.label %></li>
        <% end %>
      </ul>

      <div id="kit_info">
        <div class="form-divider"></div>

        <h4> <i class="fa fa-suitcase"></i> Recording kit</h4>
          <%= f.check_box :is_kit %> <span>This item has several items that need to be checked out together.</span>

          <% if @equipment.is_kit? %>
          <h4>Contents</h4>
          <ul class="contents-list">
            <% @equipment.sub_items.each do |item| %>
            <li><%= link_to item.name, edit_equipment_sub_item_path(@equipment, item) %></li>
            <% end %>
          </ul>
          <%= link_to new_equipment_sub_item_path(@equipment), class: 'btn btn-sm btn-success' do %>
            <i class="fa fa-plus"></i> Add Another
          <% end %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/equipment/edit.html.erb
<% provide(:title, "Editing #{@equipment.name}") %>

<ol class="breadcrumb">
	<li><%= link_to 'Equipment', equipment_index_path %></li>
	<li><%= link_to @equipment.name, @equipment %></li>
	<li class="active">Edit</li>
</ol>

<!-- ng-candidate: Live update header text, possibly do something with subitems -->
<h1 class="page-header"><%= @equipment.name %></h1>

<%= render 'form' %>

app/views/equipment/history.html.erb
<% provide(:title, "#{@equipment.name} History") %>
<h1 class="page-header"><%= @equipment.name %> History</h1>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2 print-full-width">
    <button onclick="window.print()" class="btn btn-large btn-primary pull-right print-button">
      <i class="fa fa-print"></i> Print
    </button>
    <table class="table table-striped equipment-table">
      <tbody>

        <% @equipment.reservations.where(is_denied: [false, nil]).each do |reservation| %>
        <tr>
          <td>
            <div>
              <%= render 'shared/user_reservation', reservation: reservation %>
            </div>
          </td>

          <td>
            <div class="equipment-history-comments-area">
              <% if reservation.check_out_comments %>
                <div class="equipment-history-comments">
                  <strong>Checked out by: </strong>
                  <%= reservation.checked_out_by.name %> <br />

                  <strong>Comments: </strong>
                  <%= reservation.check_out_comments %> <br />
                </div>
              <% end %>

              <% if reservation.check_in_comments %>
                <div class="equipment-history-comments">
                  <strong>Checked in by: </strong>
                  <%= reservation.checked_in_by.name %> <br />

                  <strong>Comments: </strong>
                  <%= reservation.check_in_comments %> <br />
                </div>
              <% end %>
            </div>

          </td>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/equipment/index.html.erb
<% provide(:title, 'Equipment') %>
<h1 class="page-header">Equipment List</h1>

<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <% if current_user.is_admin? %>
      <div class="button-container">
        <%= link_to categories_path, class: 'btn btn-large btn-default' do %>
          <i class="fa fa-sitemap"></i> Manage Categories
        <% end %>
        <%= link_to new_equipment_path, class: 'btn btn-large btn-primary' do %>
          <i class="fa fa-plus"></i> New Equipment
        <% end %>
      </div>
    <% end %>

    <ul class="nav nav-pills user-type-tabs">
      <li class="<%= 'active' if params[:controller] == 'equipment' %>"> <%= link_to 'All', equipment_index_path %> </li>
      <% Category.all.each do |category| %>
        <li class="<%= 'active' if params[:id] == category.id.to_s %>"> <%= link_to category.name, category %> </li>
      <% end %>
    </ul>

      <!-- ng-candidate: Have option to filter equipment the user doesn't have permission to see. (Just using JQuery works but breaks the striped look) -->
      <table id="equipment_table" class="table table-striped equipment-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Brand</th>
              <th>Quantity</th>
              <% if current_user.is_admin? %><th></th><% end %>
            </tr>
          </thead>

          <tbody>
            <% @equipment.each do |equipment| %>
              <tr <% if !equipment.can_be_checked_out_by(current_user) %> class='equipment-denied-row'<% end %>>
                <td><strong><%= link_to equipment.name, equipment %></strong></td>
                <td><%= equipment.brand %></td>
                <td><%= equipment.quantity %></td>
                <% if current_user.is_admin? %>
                  <td>
                    <%= link_to edit_equipment_path(equipment), class: 'btn btn-large' do %>
                        <i class="fa fa-pencil"></i> <span class="hide-small">Edit</span>
                    <% end %>
                    <%= link_to equipment, class: 'btn btn-large', method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <i class="fa fa-trash-o"></i> <span class="hide-small">Delete</span>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

    </div>
</div>

app/views/equipment/new.html.erb
<% provide(:title, 'New Equipment') %>

<ol class="breadcrumb">
	<li><%= link_to 'Equipment', equipment_index_path %></li>
	<li class="active">New</li>
</ol>

<h1 class="page-header">New equipment</h1>

<%= render 'form' %>

app/views/equipment/show.html.erb
<% provide(:title, @equipment.name) %>

<ol class="breadcrumb">
  <li><%= link_to 'Equipment', equipment_index_path %></li>
  <li class="active"><%= @equipment.name %></li>
</ol>

<div class="top-padding"></div>

<div class="row">
  <div class="col-sm-5">
    <div class="info">
      <h1><%= @equipment.brand %> <%= @equipment.name %></h1>

      <h4>Category</h4>
      <p><%= @equipment.category.name %></p>

      <h4>Condition</h4>
      <p><%= @equipment.condition %></p>

      <h4>Description</h4>
      <p><%= @equipment.description %></p>


      <h4>Permissions</h4>
      <ul class="permissions-list">
        <% @equipment.permissions.each do |permission| %>
          <li><%= permission.name %></li>
      <% end %>
      </ul>

      <% if @equipment.is_kit? %>
        <h4>Contents</h4>
      <ul class="contents-list">
        <% @equipment.sub_items.each do |item| %>
          <li title="<%= item.description %>"><%= item.name %> <%= '(Optional)' if item.is_optional? %></li>
      <% end %>
      </ul>
    <% end %>

    <% if current_user.is_admin? %>
      <div class="buttons">
        <%= link_to edit_equipment_path(@equipment), class: 'btn btn-large btn-primary' do %>
          <i class="fa fa-edit"></i> Edit
        <% end %>
        <%= link_to @equipment, method: :delete, class: 'btn btn-large btn-danger', data: { confirm: 'Are you sure?' } do %>
          <i class="fa fa-trash-o"></i> Delete
        <% end %>
        <%= link_to history_equipment_path(@equipment), class: 'btn btn-large btn-primary' do %>
          <i class="fa fa-archive"></i> History
        <% end %>
      </div>
    <% end %>

    </div>
  </div>
  <div class="col-sm-7">
    <div class="related-reservations">
      <%= render 'shared/user_reservation_list', reservations: @equipment.reservations.reorder('updated_at DESC').limit(5),
        title: 'Recent Reservations', empty_text: 'This equipment has not been reserved',
        show_approve_deny_buttons: false %>
    </div>
    </div>
  </div>