config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :permissions

  root 'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'welcome' => 'static_pages#welcome'
  get 'about'   => 'static_pages#about'
  get 'help'    => 'static_pages#help'
  get 'version/1.1' => 'static_pages#v1_1'
  get 'version/1.2' => 'static_pages#v1_2'

  get 'signin'  => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  resources :sessions, only: [:create, :destroy]

  get 'monitor/dashboard' => 'monitor#dashboard'
  get 'monitor' => 'monitor#dashboard'

  get 'admin/dashboard' => 'admin#dashboard'
  get 'admin' => 'admin#dashboard'

  get 'archive' => 'reservations#archive'

  resources :reservations do
    collection do
      get 'archive'
    end

    member do
      get 'approve'
      post 'deny'
      get 'checkout'
      post 'checkout_update'
      get 'checkin'
      post 'checkin_update'
    end
  end
  resources :equipment do
    member do
      get 'history'
    end

    resources :sub_items
  end
  resources :users do
    member do
      get 'password'
    end

    collection do
      get 'monitors'
      get 'admins'
    end
  end
  resources :reservation_equipment

  get 'search' => 'search#index', as: :search

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                        :integer          not null, primary key
#  name                      :string(255)
#  email                     :string(255)
#  created_at                :datetime
#  updated_at                :datetime
#  password_digest           :string(255)
#  remember_token            :string(255)
#  is_admin                  :boolean          default(FALSE)
#  is_monitor                :boolean
#  notify_on_approval_needed :boolean          default(TRUE)
#  notify_on_approved        :boolean          default(TRUE)
#  notify_on_denied          :boolean          default(TRUE)
#  notify_on_checked_out     :boolean          default(TRUE)
#  notify_on_checked_in      :boolean          default(TRUE)
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :reservations
  has_many :monitor_checkouts, foreign_key: 'checked_out_by_id', class_name: 'Reservation'
  has_many :monitor_checkins, foreign_key: 'checked_in_by_id', class_name: 'Reservation'
  has_and_belongs_to_many :permissions

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX } ,
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  # Mailing lists
  scope :approval_needed_mailing_list, -> { where(is_admin: true, notify_on_approval_needed: true) }

  def monitor_access?
    is_admin? || is_monitor?
  end

  def allowed_equipment
    ids = Set.new
    permissions.each do |p|
      p.equipment.each do |item|
        ids.add(item.id)
      end
    end

    Equipment.where(id: ids.to_a)
  end

  def first_name
    name.split(' ')[0]
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :password, :update, :destroy]
  before_filter :user_signed_in
  before_filter :user_is_admin, only: [:index, :new, :create, :destroy]
  before_filter :current_user_or_admin, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/monitors
  def monitors
    @users = User.where(is_monitor: true)
    render :index
  end

  # GET /users/admins
  def admins
    @users = User.where(is_admin: true)
    render :index
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/1/password
  def password
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        send_welcome_email
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        if params[:user][:password]
          format.html { render :password }
        end
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def send_welcome_email
      UserMailer.welcome_email(@user).deliver
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin, :is_monitor, 
                                   :notify_on_approval_needed, 
                                   :notify_on_approved, 
                                   :notify_on_denied, 
                                   :notify_on_checked_out, 
                                   :notify_on_checked_in, 
                                   permission_ids: [])
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size=80, badge=false)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{size}&d=monsterid"
    if badge
      img_class = 'gravatar gravatar-badge'
    else
      img_class = 'gravatar'
    end
    image_tag(gravatar_url, alt: user.name, class: img_class)
  end
end

app/views/users/_user.html.erb
<div class="profile-pic">
	<%= gravatar_for(user, 120) %>
</div>
<div class="profile-info">
	<h2>
		<%= link_to user.name, user %>
		<% if user.is_admin? %> <i class="fa fa-rocket" title='Administrator access'></i><% end %>
		<% if user.is_monitor? && !user.is_admin? %> <i class="fa fa-key" title='Lab Monitor access'></i><% end %>
	</h2>

	<h4>
	  <a href="mailto:<%= user.email %>"><%= user.email %></a>
	</h4>
</div>

app/views/users/edit.html.erb
<% if @user == current_user %>
	<% provide(:title, 'Settings') %>
<% else %>
	<% provide(:title, @user.name) %>
<% end %>

<% if @user != current_user %>
<ol class="breadcrumb">
	<li><%= link_to 'Admin', admin_path %></li>
	<li><%= link_to 'Users', users_path %></li>
	<li><%= link_to @user.name, @user %></li>
	<li class="active">Edit</li>
</ol>
<% end %>

<div class="top-padding"></div>

<!-- ng-candidate -->
<div class="row">
	<div class="col-sm-3 col-sm-offset-2">
		<div class="profile-pic">
			<%= gravatar_for(@user, 200) %>
			<p><em>Tip: If you don't like your monster picture, go to <a href="http://gravatar.com">gravatar.com</a> and add a different picture to an account with the same email address.</em></p>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="user-info">
			<div class="row">
				<div class="profile-info">
				<h1>
					<% if @user == current_user %>
						Settings
					<% else %>
						<%= @user.name %>
					<% end %>
				</h1>
					<%= form_for(@user) do |f| %>
					<% if @user.errors.any? %>
					    <div id="error_explanation">
					      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

					      <ul>
					      <% @user.errors.full_messages.each do |message| %>
					        <li><%= message %></li>
					      <% end %>
					      </ul>
					    </div>
					  <% end %>
						<%= f.label :name %>
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-user"></i></span>
							<%= f.text_field :name, class: "form-control" %>
						</div>

						<%= f.label :email %>
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
							<%= f.email_field :email, class: "form-control" %>
						</div>

						<% if current_user.is_admin? %>
							<h3>Permissions</h3>
							<div class="form-divider"></div>

							<ul class="permissions-list">
								<%= f.collection_check_boxes :permission_ids, Permission.all, :id, :name do |ff| %>
								<li><%= ff.check_box %> <%= ff.label %></li>
								<% end %>
							</ul>

							<% if current_user.is_admin? && @user != current_user %>
								<div class="form-divider"></div>
								<h4>Site Permissions</h4>
								<ul class="permissions-list">
									<li><%= f.check_box :is_monitor %> <%= f.label :is_admin, 'Lab Monitor access' %></li>

									<!-- Don't give admins the option to un-admin themselves -->
									<% if @user != current_user %>
										<li><%= f.check_box :is_admin %> <%= f.label :is_admin, 'Administrator access' %></li>
									<% end %>
								</ul>
							<% end %>
						<% end %>

            <% if @user == current_user %>
              <h4>Email Notifications <i class="fa fa-envelope"></i> </h4>
              <div class="form-divider"></div>

              <ul class="permissions-list">
                <% if current_user.is_admin? %>
                  <li><%= f.check_box :notify_on_approval_needed %> <%= f.label :notify_on_approval_needed, 'When a reservation requires admin approval' %></li>
                <% end %>
                <li><%= f.check_box :notify_on_approved %> <%= f.label :notify_on_approved, 'When my reservation gets approved' %></li>
                <li><%= f.check_box :notify_on_denied %> <%= f.label :notify_on_denied, 'When my reservation gets denied' %></li>
                <li><%= f.check_box :notify_on_checked_out %> <%= f.label :notify_on_checked_out, 'When my reservation gets checked out' %></li>
                <li><%= f.check_box :notify_on_checked_in %> <%= f.label :notify_on_checked_in, 'When my reservation gets returned' %></li>
              </ul>
            <% end %>

						<%= f.submit "Submit" , class: "btn btn-large btn-primary" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Admin', admin_path %></li>
  <li class="active">Users</li>
</ol>

<h1 class="page-header">Users</h1>

<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="button-container">
      <%= link_to new_user_path, class: 'btn btn-large btn-primary' do %>
        <i class="fa fa-plus"></i> New User
      <% end %>
    </div>

    <ul class="nav nav-pills user-type-tabs">
      <li class="<%= 'active' if params[:action] == 'index' %>"><%= link_to 'All', users_path %></li>
      <li class="<%= 'active' if params[:action] == 'monitors' %>"><%= link_to 'Monitors', monitors_users_path %></li>
      <li class="<%= 'active' if params[:action] == 'admins' %>"><%= link_to 'Admins', admins_users_path %></li>
    </ul>
    <table id="all_users" class="table table-striped">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <div class="profile-pic"><%= gravatar_for(user, 50) %></div>
              <div class="profile-info">
                <%= link_to user do %>
                    <h4><%= user.name %>
                      <% if user.is_admin? %> <i class="fa fa-rocket" title='Administrator access'></i><% end %>
                      <% if user.is_monitor? && !user.is_admin? %> <i class="fa fa-key" title='Lab Monitor access'></i><% end %>
                    </h4>
                <% end %>

                <h5>
                  <a href="mailto:<%= user.email %>"><%= user.email %></a>
                </h5>
              </div>
            </td>
            <td>
              <%= link_to edit_user_path(user), class: 'btn btn-large' do %>
                  <i class="fa fa-pencil"></i> Edit
              <% end %>
              <%= link_to user, class: 'btn btn-large', method: :delete, data: { confirm: 'Are you sure?' } do %>     <i class="fa fa-trash-o"></i> Delete
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

app/views/users/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Admin', admin_path %></li>
  <li><%= link_to 'Users', users_path %></li>
  <li class="active">New</li>
</ol>

<h1 class="page-header">New user</h1>

<div class="row">
  <%= form_for(@user) do |f| %>
    <div class="col-sm-6 col-sm-offset-1">
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <div class="input-group">
      <span class="input-group-addon"><span class="fa fa-user"></span></span>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <%= f.label :email %>
    <div class="input-group">
      <span class="input-group-addon">@</span>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <%= f.label :password %>
    <div class="input-group">
      <span class="input-group-addon"><span class="fa fa-lock"></span></span>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <%= f.label :password_confirmation %>
    <div class="input-group">
      <span class="input-group-addon"><span class="fa fa-lock"></span></span>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
  </div>

  <div class="col-sm-4">
    <h3>Permissions</h3>
    <div class="form-divider"></div>

    <ul class="permissions-list">
      <%= f.collection_check_boxes :permission_ids, Permission.all, :id, :name do |ff| %>
        <li><%= ff.check_box %> <%= ff.label %></li>
    <% end %>
    </ul>

    <div class="form-divider"></div>

    <ul class="permissions-list">
      <li><%= f.check_box :is_monitor %> <%= f.label :is_admin, 'Lab Monitor access' %></li>

      <li><%= f.check_box :is_admin %> <%= f.label :is_admin, 'Administrator access' %></li>
    </ul>
  </div>
<% end %>
</div>

app/views/users/password.html.erb
<% provide(:title, 'Reset Password') %>

<% if @user != current_user %>
<ol class="breadcrumb">
	<li><%= link_to 'Admin', admin_path %></li>
	<li><%= link_to 'Users', users_path %></li>
	<li><%= link_to @user.name, @user %></li>
	<li class="active">Edit Password</li>
</ol>
<% end %>

<div class="top-padding"></div>

<div class="row">
	<div class="col-sm-3 col-sm-offset-2">
		<div class="profile-pic">
			<%= gravatar_for(@user, 200) %>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="user-info">
			<div class="row">
				<div class="profile-info">
				<h1>Reset Password</h1>
					<%= form_for(@user) do |f| %>
						<%= render 'shared/error_messages', object: f.object %>
						<%= f.label :password %>
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-lock"></i></span>
							<%= f.password_field :password, class: "form-control" %>
						</div>

						<%= f.label :password_confirmation %>
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-lock"></i></span>
							<%= f.password_field :password_confirmation, class: "form-control" %>
						</div>
					
						<%= f.submit "Reset" , class: "btn btn-large btn-primary" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
  <% provide(:title, 'Profile') %>
<% else %>
  <% provide(:title, @user.name) %>
<% end %>

<% if @user != current_user %>
  <ol class="breadcrumb">
  <li><%= link_to 'Admin', admin_path %></li>
  <li><%= link_to 'Users', users_path %></li>
  <li class="active"><%= @user.name %></li>
</ol>
<% end %>

<div class="top-padding"></div>

<div class="row">
  <div class="col-sm-5">
    <div class="info">
      <div class="profile-pic">
        <%= gravatar_for(@user, 120) %>
      </div>
      <div class="profile-info">
        <h2><%= @user.name %>
        <% if @user.is_admin? %> <i class="fa fa-rocket" title='Administrator access'></i>
          <% end %>
          <% if @user.is_monitor? && !@user.is_admin? %> <i class="fa fa-key" title='Lab Monitor access'></i>
          <% end %>

        </h2>

        <h4>
          <a href="mailto:<%= @user.email %>"><%= @user.email %></a>
        </h4>

        <h4 class="inline-header">Permissions</h4>
        <ul class="permissions-list">
          <% @user.permissions.each do |permission| %>
            <li><%= permission.name %></li>
        <% end %>
        </ul>
      </div>


      <div class="buttons">
        <%= link_to edit_user_path(@user), class: 'btn btn-large btn-primary' do %>
          <i class="fa fa-edit"></i> Edit
      <% end %>
        <%= link_to password_user_path(@user), class: 'btn btn-large btn-primary' do %>
          <i class="fa fa-lock"></i> Reset Password
      <% end %>
        <% if current_user.is_admin? && current_user != @user %>
          <%= link_to @user, method: :delete, class: 'btn btn-large btn-danger', data: { confirm: 'Are you sure?' } do %>
          <i class="fa fa-trash-o"></i> Delete
      <% end %>
      <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-7">
    <div class="related-reservations">
      <%= render 'shared/icon_reservation_list', reservations: @user.reservations.reorder('updated_at DESC').limit(5), title: 'Recent Reservations' %>
    </div>
  </div>
</div>