config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :permissions

  root 'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'welcome' => 'static_pages#welcome'
  get 'about'   => 'static_pages#about'
  get 'help'    => 'static_pages#help'
  get 'version/1.1' => 'static_pages#v1_1'
  get 'version/1.2' => 'static_pages#v1_2'

  get 'signin'  => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  resources :sessions, only: [:create, :destroy]

  get 'monitor/dashboard' => 'monitor#dashboard'
  get 'monitor' => 'monitor#dashboard'

  get 'admin/dashboard' => 'admin#dashboard'
  get 'admin' => 'admin#dashboard'

  get 'archive' => 'reservations#archive'

  resources :reservations do
    collection do
      get 'archive'
    end

    member do
      get 'approve'
      post 'deny'
      get 'checkout'
      post 'checkout_update'
      get 'checkin'
      post 'checkin_update'
    end
  end
  resources :equipment do
    member do
      get 'history'
    end

    resources :sub_items
  end
  resources :users do
    member do
      get 'password'
    end

    collection do
      get 'monitors'
      get 'admins'
    end
  end
  resources :reservation_equipment

  get 'search' => 'search#index', as: :search

end

app/models/sub_item.rb
# == Schema Information
#
# Table name: sub_items
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  brand       :string(255)
#  kit_id      :integer
#  description :text
#  is_optional :boolean
#  created_at  :datetime
#  updated_at  :datetime
#

class SubItem < ActiveRecord::Base
  belongs_to :kit, class_name: 'Equipment'
  has_and_belongs_to_many :reservations

  validates :name, presence: true
  validates :description, presence: true
  validates :kit_id, presence: true
end

app/controllers/sub_items_controller.rb
class SubItemsController < ApplicationController
  before_action :set_kit
  before_action :set_sub_item, only: [:show, :edit, :update, :destroy]

  # GET /sub_items
  # GET /sub_items.json
  def index
    @sub_items = SubItem.all
  end

  # GET /sub_items/1
  # GET /sub_items/1.json
  def show
    redirect_to @kit
  end

  # GET /sub_items/new
  def new
    @sub_item = @kit.sub_items.build
  end

  # GET /sub_items/1/edit
  def edit
  end

  # POST /sub_items
  # POST /sub_items.json
  def create
    @sub_item = SubItem.new(sub_item_params)
    @sub_item.kit = @kit
    respond_to do |format|
      if @sub_item.save
        format.html { redirect_to @kit, notice: 'Sub item was successfully created.' }
        format.json { render :show, status: :created, location: @sub_item }
      else
        format.html { render :new }
        format.json { render json: @sub_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_items/1
  # PATCH/PUT /sub_items/1.json
  def update
    respond_to do |format|
      if @sub_item.update(sub_item_params)
        format.html { redirect_to @kit, notice: 'Sub item was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_item }
      else
        format.html { render :edit }
        format.json { render json: @sub_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_items/1
  # DELETE /sub_items/1.json
  def destroy
    @sub_item.destroy
    respond_to do |format|
      format.html { redirect_to @kit, notice: 'Sub item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kit
      @kit = Equipment.find(params[:equipment_id])
    end

    def set_sub_item
      @sub_item = SubItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_item_params
      params.require(:sub_item).permit(:name, :brand, :kit, :description, :is_optional)
    end
end

app/helpers/sub_items_helper.rb
module SubItemsHelper
end

app/views/sub_items/_form.html.erb
<%= form_for([@kit, @sub_item]) do |f| %>
  <% if @sub_item.errors.any? %>
    <%= render 'shared/error_messages', object: f.object %>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.check_box :is_optional %>
    <%= f.label :is_optional %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-large btn-success' %>
    <% if params[:action] == 'edit' %>
      <%= link_to equipment_sub_item_path(@kit, @sub_item), method: :delete, class: 'btn btn-large btn-danger', data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash-o"></i> Delete
      <% end %> 
    <% end %>
  </div>
<% end %>

app/views/sub_items/edit.html.erb
<% provide(:title, "Editing #{@sub_item.name}") %>

<ol class="breadcrumb">
	<li><%= link_to 'Equipment', equipment_index_path %></li>
	<li><%= link_to @kit.name, @kit %></li>
	<li><%= link_to @sub_item.name, equipment_sub_item_path(@kit, @sub_item) %></li>
	<li class="active">Edit</li>
</ol>

<div class="top-padding"></div>

<div class="row">
	<div class="col-sm-6 col-sm-offset-1">
		<h1>Editing <%= @sub_item.name %></h1>
		<%= render 'form' %>
	</div>
	<div class="col-sm-4">
		<div class="kit-side-info">
			<h2><%= @kit.name %></h2>
			
			<h4 class="kit-side-description"><%= @kit.description %></h4>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Contents</h3>
			</div>
			<ul class="list-group">
				<% @kit.sub_items.each do |item| %>
				<li class="list-group-item"><%= link_to item.name, edit_equipment_sub_item_path(@kit, item) %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/sub_items/index.html.erb
<h1>Listing sub_items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Kit</th>
      <th>Description</th>
      <th>Is optional</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_items.each do |sub_item| %>
      <tr>
        <td><%= sub_item.name %></td>
        <td><%= sub_item.brand %></td>
        <td><%= sub_item.kit %></td>
        <td><%= sub_item.description %></td>
        <td><%= sub_item.is_optional %></td>
        <td><%= link_to 'Show', sub_item %></td>
        <td><%= link_to 'Edit', edit_sub_item_path(sub_item) %></td>
        <td><%= link_to 'Destroy', sub_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub item', new_sub_item_path %>

app/views/sub_items/new.html.erb
<% provide(:title, 'New Sub-Item') %>

<ol class="breadcrumb">
	<li><%= link_to 'Equipment', equipment_index_path %></li>
	<li><%= link_to @kit.name, @kit %></li>
	<li class="active">New</li>
</ol>

<div class="top-padding"></div>

<div class="row">
	<div class="col-sm-6 col-sm-offset-1">
		<h1>New Sub-item</h1>
		<%= render 'form' %>
	</div>
	<div class="col-sm-4">
		<div class="kit-side-info">
			<h2><%= @kit.name %></h2>
			
			<h4 class="kit-side-description"><%= @kit.description %></h4>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Contents</h3>
			</div>
			<ul class="kit-side-permissions-list list-group">
				<% @kit.sub_items.each do |item| %>
					<% if item.id %>
					<li class="list-group-item"><%= link_to item.name, edit_equipment_sub_item_path(@kit, item) %></li>
					<% end %>
				<% end %>
			</ul>
		</div>
	</div>
</div>